name: 'create release note'
description: 'this action collect issues by tag name and create release note.'
inputs:
  github-token:
    description: 'GITHUB_TOKEN'
    required: true
  tag:
    description: 'target tag'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'file-text'
  color: 'gray-dark'
